export const SET_TIMESHEET_SHCEDULED_HOURS = 'SET_TIMESHEET_SHCEDULED_HOURS';
export const SET_LOADING = 'SET_LOADING';
export const SET_MESSAGE = 'SET_MESSAGE';
export const IN_PROGRESS_TIMESHEET = 'IN_PROGRESS_TIMESHEET';
